spring.datasource.url=jdbc:mysql://localhost:3306/data?
spring.datasource.username=Partha
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:2222}



#spring.application.name=DataRecord 
#spring.jpa.hibernate.ddl-auto=update 
#spring.datasource.url=jdbc:mysql://localhost:3308/Data
#spring.datasource.username=Partha 
#spring.datasource.password=partha3 

# Remote MySQL (Not working)
#spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:20382/railway?useSSL=false&serverTimezone=UTC 
#spring.datasource.username=root 
#spring.datasource.password=inWonTCIJlyBygvTIoppXoZfsaBeIeQu 
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver \u2028#spring.jpa.show-sql=true 

# Local H2 Database 
#spring.datasource.url=jdbc:h2:mem:testdb 
#spring.datasource.driverClassName=org.h2.Driver 
#spring.datasource.username=sa spring.datasource.password=password 
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect spring.h2.console.enabled=true

